### ISSUE TITLE
/*jshint ignore:start*/ does not ignore W101 "Line is too long."

### ISSUE THREAD

**Issue by victor-homyakov** [jshint/jshint#1575]
Region of code marked with `/*jshint ignore:start*/ ... /*jshint ignore:end*/` in JSHint 2.4.4 still may produce warning "Line is too long." for commented line

Code to completely ignore warnings in some region of code looks like

    /*jshint ignore:start,-W101*/
    // third-party code
    // this very very very very very very very very very very very very very long comment line will produce warning "Line is too long." unless W101 is explicitly disabled
    /*jshint ignore:end,+W101*/

**Comment by spirosdi** [comment]
It seems that issue still appears when using grunt-contrib-jshint v0.11.0 which uses jshint v ~2.6.0

**Comment by lukeapage** [comment]
you are right. test case:
```
/* jshint maxlen: 50 */
/*jshint ignore:start*/
// third-party code
// this very very very very very very very very very very very very very long comment line will produce warning "Line is too long." unless W101 is explicitly disabled
/*jshint ignore:end*/
```

**Comment by lukeapage** [comment]
may be also fixed by #2477

**Comment by lukeapage** [comment]
*not* fixed by #2512

**Comment by simonv3** [comment]
This is still happening for me in 2.9.2

```
/* jshint ignore:start */
// Look at https://github.com/jasmine/jasmine/blob/f6da0846423a08959b5602a630d419e3059283aa/src/core/matchers/toHaveBeenCalledWith.js
/* jshint ignore:end */
```

We use a .jshint.rc file in our case. 

But using /* jshint -W101 */ before the line does work, so this isn't urgent for me.

**Comment by englishextra** [comment]
This is not  fixed yet

**Comment by jugglinmike** [comment]
@englishextra I cannot reproduce the erroneous warning in JSHint version 2.9.2
or 2.9.4 (the latest as of this writing). Can you please share a complete program
that demonstrates the bug? Be sure to include the necessary configuration as an
in-line directive (e.g. `/* jshint maxlen: 50 */`).

**Comment by englishextra** [comment]
Well the idea is to hide masonry lib from linting

https://gist.github.com/englishextra/f1cc7d27876773f206081a2fd261be01

In my case it appears not to ignore the commented code

https://gist.github.com/englishextra/f1cc7d27876773f206081a2fd261be01
