### ISSUE TITLE
Incorrect warning I003, when using .jshintrc with option "enforceall"

### ISSUE THREAD

**Issue by dr15x86** [jshint/jshint#2251]
If you use JSHint with .jshintrc or CLI argument `--config` with option `"enforceall": true`. And then in the JS file, leave any comment with the JSHint option, JSHint displays a warning `ES5 option is now set per default (I003)`.

###### How test
Create 2 files:
`.jshintrc`
```JSON
{
    "enforceall": true
}
```

and `test.js`
```javascript
/* jslint browser: true */
```

run `jshint test.js`:

        /tmp/jshint/bin/jshint test.js 
        test.js: line 1, col 1, ES5 option is now set per default
        
        1 error

**Comment by jawshooah** [comment]
:+1: , this is extremely annoying.

**Comment by caitp** [comment]
hopefully this isn't failing builds --- but yeah, I'll try to put together a fix tonight

**Comment by caitp** [comment]
this appears to have been fixed, I can't reproduce with master

**Comment by jawshooah** [comment]
I have master checked out, and I'm still having problems.

Config:
```json
{
  "enforceall": true
}
```
JavaScript:
```
/* jshint node:true */
```
Output:
```bash
$ bin/jshint foo.js
foo.js: line 1, col 1, ES5 option is now set per default

1 error
```

**Comment by david-gang** [comment]
:+1:
