### ISSUE TITLE
camelcase overwrite on /*jshint camelcase:false */ doesn work on 2.6.3

### ISSUE THREAD

**Issue by gonmercado** [jshint/jshint#2255]
Hi, i've tried with 2.5.11 and 2.6.3, and  i have in my global config:
"camelcase": true,

but in one file an overwrite to a single function 
 /*jshint camelcase:false */
if(response.data.error.frontend_show_in_popup)

The problem is that in 2.6.3 still warns me about the non camel case variable.
In the version 2.5.11 is working ok, it doesn't warn me about the camel case.

Is that a bug? or it changed how to implement it on the source code?

Thanks

**Comment by caitp** [comment]
it doesn't look to me like there's any way to prevent the style module from running (which is really weird since it's deprecated), and no way to control which specific style linters are run. And, during `doOption()` it doesn't look like any linters are re-configured, so yeah.

if that worked before, I guess something changed. Weird that we are running it at all though

**Comment by swashcap** [comment]
Seeing this problem, too. Unfortunately, adding inline ignore directives…

```js
/* jshint ignore:start */
output.apiResponse = result.my_silly_underscore_api_response
/* jshint ignore:end */
```

…still results in the `Identifier 'my_silly_underscore_api_response' is not in camel case.` error.

**Comment by ZengineAlex** [comment]
I also get this error. Setting camel case to false in the line or ignoring the line still does not work.

**Comment by jpangburn** [comment]
Still broken in 2.8.0, worked fine for me in 2.5.11.  Tried both the previously working /*jshint camelcase: false */ and the ignore start/end.

**Comment by nicolo-ribaudo** [comment]
This has been fixed in #2664

**Comment by slavede** [comment]
Wouldn't say so, I just upgraded to 2.8.0, still broken...I had to put ignore:line

**Comment by jugglinmike** [comment]
@slavede The fix has not yet been released, but you can expect it in version 2.9.1. If you'd like to vet our release candidate, you may try 2.9.1-rc2 today.

**Comment by yogeshsajanikar** [comment]
Is this issue fixed yet. I am getting this issue in jshint 2.9.1

**Comment by jugglinmike** [comment]
@yogeshsajanikar The patch (including tests for this use case) was released as part of JSHint version 2.9.1 (mea culpa for forgetting to close this issue). Can you provide an example of the input that triggers the incorrect warning?

**Comment by yogeshsajanikar** [comment]
Confirm that this is indeed fixed in 2.9.1, I was getting error because of mismatch of grunt-config-jshint version.

**Comment by jugglinmike** [comment]
Excellent! Closing as resolved

**Comment by jpangburn** [comment]
2.9.1 fixed this for me too, thanks!
